app:
  auth:
    token-secret: ${TOKEN_SECRET} # JWT를 암호화하기 위한 암호화 키
    refresh-cookie-key: ${REFRESH_COOKIE_KEY}
    token-expiration-msec: ${TOKEN_EXPIRATION_MSEC}  # token 만료 기간 (24h * 60min * 60s * 1000ms)

oauth2:
  # OAuth2 공급자로 성공적으로 인증 한 후 사용자에 대한 인증 토큰을 생성하고 토큰을
  # 프론트 엔드 클라이언트가 /oauth2/authorize 요청에서 지정한 redirectUri 입니다.
  authorized-redirect-uris: ${AUTHORIZED_REDIRECT_URIS}