package swmaestro.spaceodyssey.weddingmate.global.exception.handler;

import static org.springframework.http.HttpStatus.*;

import org.springframework.http.HttpStatus;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

	/* Common */
	// Basic - C0***
	RUNTIME_EXCEPTION(BAD_REQUEST, "C0001", "RUNTIME_EXCEPTION"),

	// Oauth - C1***
	OAUTH_PROVIDERID_NOTFOUND(NOT_FOUND, "C1001", "OAUTH_PROVIDERID_NOTFOUND"),
	OAUTH_DUPLICATE_EMAIL(CONFLICT, "C1002", "OAUTH_DUPLICATE_EMAIL"),
	OAUTH_UNAUTHORIZED_URL(UNAUTHORIZED, "C1003", "OAUTH_UNAUTHORIZED_URL"),

	// User - C2***
	USER_NOTFOUND(NOT_FOUND, "C2001", "USER_NOTFOUND"),
	USER_NAME_NOTFOUND(NOT_FOUND, "C2002", "USER_NAME_NOTFOUND"),
	USER_UNAUTHORIZED(UNAUTHORIZED, "C2003", "USER_UNAUTHORIZED"),

	// Planner - C21**
	PLANNER_NOTFOUND(NOT_FOUND, "C2101", "PLANNER_NOTFOUND"),
	PLANNER_DUPLICATE_REGISTRATION(CONFLICT, "C21002", "PLANNER_DUPLICATE_REGISTRATION"),

	// Customer - C22**
	CUSTOMER_DUPLICATE_REGISTRATION(CONFLICT, "C22002", "PLANNER_DUPLICATE_REGISTRATION"),
	CUSTOMER_NOTFOUND(NOT_FOUND, "C22001", "CUSTOMER_NOTFOUND"),

	// Profile - C23**
	PLANNER_PROFILE_NOTFOUND(NOT_FOUND, "C2301", "PLANNER_PROFILE_NOTFOUND"),
	PROFILE_MODIFICATION_NOT_ALLOWED(FORBIDDEN, "C2302", "PROFILE_MODIFICATION_NOTALLOWED"),

	// Token - C3***
	REFRESH_TOKEN_UNAUTHORIZED(UNAUTHORIZED, "C3001", "REFRESH_TOKEN_UNAUTHORIZED"),
	REFRESH_TOKEN_NOTFOUND(NOT_FOUND, "C3002", "REFRESH_TOKEN_NOTFOUND"),
	REFRESH_TOKEN_COOKIE_NOTFOUND(NOT_FOUND, "C3003", "REFRESH_TOKEN_COOKIE_NOTFOUND"),

	// Portfolio - C4***

	PORTFOLIO_NOTFOUND(NOT_FOUND, "C4001", "PORTFOLIO_NOTFOUND"),
	ITEM_NOTFOUND(NOT_FOUND, "C4002", "ITEM_NOTFOUND"),

	// Category - C5***
	CATEGORY_NOTFOUND(NOT_FOUND, "C5001", "CATEGORY_NOTFOUND"),

	// File - C6***
	FILE_NOTFOUND(NOT_FOUND, "C6001", "FILE_NOTFOUND"),
	FILE_NAME_EMPTY(BAD_REQUEST, "C6002", "FILE_NAME_EMPTY"),
	FILE_NOT_IMAGE(UNSUPPORTED_MEDIA_TYPE, "C6003", "FILE_NOT_IMAGE"),
	FILE_UNSUPPORTED_EXTENSION(UNSUPPORTED_MEDIA_TYPE, "C6004", "UNSUPPORTED_FILE_EXTENSION"),
	FILE_UPLOAD_FAILURE(INTERNAL_SERVER_ERROR, "C6005", "FILE_UPLOAD_FAILURE"),
	FILE_MALFORMED_URL(BAD_REQUEST, "C6006", "FILE_MALFORMED_URL"),
	FILE_KAKAO_PROFILE_DOWNLOAD_FAILURE(INTERNAL_SERVER_ERROR, "C6007", "FILE_KAKAO_PROFILE_DOWNLOAD_FAILURE"),

	// Like - C7***
	LIKE_TYPE_NOT_SUPPORTED(BAD_REQUEST, "C7001", "LIKE_TYPE_NOT_SUPPORTED"),

	// CHAT - C8***
	CHATROOM_NOT_AUTHORIZED(FORBIDDEN, "C8001", "NOT_CHATROOM_USER"),
	CHATROOM_NOTFOUND(NOT_FOUND, "C8002", "CHATROOM_NOT_FOUND");

	/* EXCEPTION */

	private final HttpStatus status;
	private final String code;
	private final String message;
}
